tourapi:
  base-url: https://apis.data.go.kr/B551011/KorService1/areaBasedList2
  service-key: "tYu2ASMUNpTRGpR6+M3QuT8REPkbiUJCUM4zFhFFCDDLMETQY5n8K0B/31XV/blCnhmRp5fSlntXLrRsR/6jfw=="
  mobile-os: ETC
  mobile-app: hipstour
#  default-rows: 100
#  default-page: 1
  type: json

sync:
  schedule:
    cron: "0 0 1 * * *"


spring:
  jpa:
    hibernate:
      ddl-auto: update