INSERT INTO region_info (REGION_ID, CREATED_AT, UPDATED_AT, REGION_NAME)
VALUES (1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'seoul');
INSERT INTO region_info (REGION_ID, CREATED_AT, UPDATED_AT, REGION_NAME)
VALUES (2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'incheon');


INSERT INTO USER_INFO(CREATED_AT , UPDATED_AT ,  USER_ID, NICK_NAME)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 'ROOT');

INSERT INTO task_info(TASK_ID, CREATED_AT, UPDATED_AT, DESCRIPTION )
VALUES (1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'ROOT');

INSERT INTO ROLE_INFO(ROLE_ID, CREATED_AT, UPDATED_AT, DESCRIPTION )
VALUES (1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'ROOT ROLE');

INSERT INTO ROLE_TASK_INFO (ROLE_ID, ROLE_TASK_ID , TASK_ID ,CREATED_AT, UPDATED_AT)
VALUES (1, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO USER_ROLE (ROLE_ID, CREATED_AT, UPDATED_AT, USER_ID, USER_ROLE_ID)
VALUES (1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1);


